jenkins-x/jx-pipelines-visualizer

store.go
web/templates/home.tmpl

I found the home page was barfing with an index out of bounds error if there were less than 3 pipelines in a cluster

fix: avoid failing if less than 3 pipelines

---

web/static/app.css
web/templates/pipeline.tmpl

Some explanations :
As you can see, the CPU (purple line on the top) was completely overloaded with CSS [layouts](https://developers.google.com/web/fundamentals/performance/rendering). This happens when we modify the DOM or when we change a CSS rule.
And we modified the DOM (with innerHTML) a huge number of time by second 🔥 .
So now, we request an animation frame to change the DOM (it's better because it's the good time to change something on CSS or in the DOM) and we buffer logs during this time.
And we use [insertAdjacentHTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML) which is better than innerHTML 😉 .
It's not perfect, but it's better I think 😄 
I will create in another PR some [Collapse component](https://ant.design/components/collapse/) to avoid to …

perf: Improve logs performance 

---

charts/jx-pipelines-visualizer/templates/rbac.yaml
charts/jx-pipelines-visualizer/values.yaml

for integration with cloud workload identity on GKE/EKS

fix: allow annotations to be added to the ServiceAccount

---

web/static/app.css
web/static/pipeline/index.js
web/static/pipeline/main.css
web/templates/pipeline.tmpl

Now, you can choose between light or dark color theme to display logs.
This information is saved inside your localstorage.

feat: Add color switch theme for logs

---

web/handlers/router.go

fixes #32
the regexp for the owner and repo names was too restrictive, and didn't allow dots. this is now fixed, because we're now using the default regexp, which allow everything except the `/` character

fix: repos with dots are now supported

---

charts/jx-pipelines-visualizer/templates/deployment.yaml
charts/jx-pipelines-visualizer/values.yaml

- When reading from AWS S3, `AWS_REGION` must be set as an environment variable. So let's add `env` to the chart.
- When using IAM Roles for Service Accounts for `jx-pipelines-visualizer`, the web token is mounted as a read only volume to `/var/run/secrets/eks.amazonaws.com/serviceaccount/`. Let's set `fsGroup` so that `jx` user can read those volumes.

feat: Read from log storage in AWS S3 using workload identity

---

README.md
charts/jx-pipelines-visualizer/templates/ingress.yaml
charts/jx-pipelines-visualizer/values.yaml

fixes #39 
- Fix indentation issue between ingress & secret when tls is enabled
- Fix issue when using existing secret for tls when using helm chart
Warning, structure of secrets section in values.yaml is different to be able to have multiple secret if using multiple host for jx pipelines visualizer. So i also updated README.md but i can break changes for existing configuration when using new version.

fix: fix ingress & tls syntax #39

---

web/handlers/router.go

previously, only the endpoints without final slash were valid.
if you put a final slash, it would return a 404.
this is now fixed, and both will answer.

fix: allow urls with or without final slash

---

pipeline.go

even if a pipeline has no start time yet, fallback to the creation time of the pipelineactivity

fix: always set a start time for pipelines

---

charts/jx-pipelines-visualizer/templates/deployment.yaml
charts/jx-pipelines-visualizer/values.yaml
cmd/server/main.go
go.mod
go.sum
web/handlers/pipeline.go
web/handlers/router.go
web/static/pipeline/index.js
web/templates/pipeline.tmpl

if the build controller stores pipelines in the long-term storage alongside the logs, we can retrieve them to display "old" pipelines

feat: read pipelines from long-term storage

---

Makefile
cmd/server/main.go
internal/version/version.go
store.go
web/handlers/functions/app.go
web/handlers/router.go
web/templates/archived_logs.tmpl
web/templates/home.tmpl
web/templates/layout.tmpl
web/templates/pipeline.tmpl

- add a query string with the version on our static resources, to avoid caching issue between releases
- don't recompile the go templates each time (unless we're in dev mode)

fix: don't cache static resources between releases

---

web/handlers/pipelinerun.go
web/handlers/router.go

related to #54
if the pipelineruns handler doesn't find a pipelinerun or a matching pipelineactivity, then it should return a 404 instead of trying to render the archived logs template without any data.
the real fix for #54 should be to store the pipelineruns in the long-term storage, so we can retrieve them even if the pipelinerun has been garbage collected - see https://github.com/jenkins-x-plugins/jx-build-controller/issues/13

fix: pipelinerun handler should fail cleanly

---

informer.go
pipeline.go

when filtering PipelineActivities managed by static Jenkins, don't use the "context", but the build url / build logs url.
otherwise, non-Jenkins managed PA won't be visible (for example PA created by `jx start pipeline` without using the context flag...)

fix: filter for pipelines managed by static jenkins

---

web/static/app.css

Looks like Safari is miscalculating the height of an item in a flexbox. With this little tricks, we force the size of the element.
Tested on Chrome, Safari, Opera and Firefox.
Resolve #82

fix: CSS flexbox bug in safari

---

charts/jx-pipelines-visualizer/templates/deployment.yaml
charts/jx-pipelines-visualizer/values.yaml
cmd/server/main.go
web/handlers/pipelinerun.go
web/handlers/router.go

load pipelineruns from the long-term storage, so that we don't answer with 404 once the pipelineruns have been garbage-collected from the cluster
see https://github.com/jenkins-x-plugins/jx-build-controller/issues/13
and https://github.com/jenkins-x-plugins/jx-build-controller/pull/27

feat: support archived pipelineruns

---

README.md
web/handlers/router.go
web/handlers/shields_io.go

fixes #110
see https://shields.io/endpoint for the documentation
the new custom endpoint is `/{owner}/{repo}/{branch}/shields.io` - for example `/my-org/my-repo/master/shields.io`

feat: status badge for shields.io

---

charts/jx-pipelines-visualizer/templates/deployment.yaml
charts/jx-pipelines-visualizer/values.yaml

This feature is required to access logs stored in minio which doesn't use service accounts for auth but instead uses env vars

feat: support pod.envFrom in values, for example to provide minio creds

---

web/static/pipeline/index.js

@jstrachan mentioned a problem with the origin of the URL such as: `https://login:password@host.com/`.
So, before making a fetch, we removed the `login:password` from the origin before.

fix: Remove login:pass from origin if needed

---

web/handlers/functions/links.go
web/handlers/functions/pipeline.go
web/handlers/router.go
web/templates/pipeline.tmpl

fixes #124
we used to support "external" links (to repos, author, PRs, commits, ...) only to github, I've now added support for gitlab and bitbucket (cloud) too

fix: support links to gitlab and bitbucket

---

web/static/pipeline/index.js

fixes #126
ensure we won't get a javascript error if the current step is not (yet) defined - which happens before we get the logs for the first step.
this happens if the pod takes some time to get scheduled, and the user opens the logs in that time

fix: javascript error in the pipeline logs

---

charts/jx-pipelines-visualizer/templates/ingress.yaml

we need to scope values so we can access them in them here, this link helped with the fix https://stackoverflow.com/a/56671939/5010477
fixes the downsteam CI failure https://github.com/jenkins-x/jx3-versions/pull/2825

fix: default Jenkins X config with host is failing with recent path changes

---

README.md
charts/jx-pipelines-visualizer/values.yaml
cmd/server/main.go
pipeline.go
store.go
web/handlers/functions/links.go
web/handlers/logs.go
web/handlers/logs_live.go
web/handlers/pipeline.go
web/handlers/pipelinerun.go
web/handlers/router.go
web/static/pipeline/main.css
web/templates/archived_logs.tmpl
web/templates/home.tmpl
web/templates/pipeline.tmpl

**Features:**
- Adds additional prefixed endpoints that includes namespace name
- Backwards compatiblility with non-prefixed links (could be deprecated and removed in future)
- Prints namespace in job execution details
- By default listens on all namespaces
- **Visualizer can now show pipelines in scope of single namespace, or cluster-wide**. Can be installed per-team-namespace or as a central viewer. Defaults to central viewer as Jenkins X does not support installation per-namespace
Part of https://github.com/jenkins-x/lighthouse/pull/1424
--------------------------------------------------------------------------

feat: Support for multiple namespaces with preserving backwards comability
