jenkins-x/jx-pipelines-visualizer

go.mod
go.sum
web/handlers/pipelinerun.go
web/handlers/router.go

for easier integration with lighthouse + tekton engine
fixes #7

fix: add a tekton dashboard style path for PipelineRuns

---

.goreleaser.yml
Dockerfile
charts/jx-pipelines-visualizer/values.yaml
cmd/server/main.go
hack/changelog-header.md

- container not running as root
- fix release header
- fix goreleaser LD flags

fix: various small fixes

---

web/templates/pipeline.tmpl

fix: add breadcrumb links

---

web/static/app.css
web/static/pipeline/index.js
web/static/pipeline/main.css
web/templates/pipeline.tmpl

💄 UI improvements:
- Add checkbox to follow logs. Fix #17.
- Add sticky bar with links and options (for the moment, checkbox to follow logs). Fix #16.
- Add line number and anchor. The UI will scroll down to the good line number. Fix #15.
- Logs are in a light color theme => I will create 2 different color theme and let the user choose 😉.
- Refresh colors (red, green, blue) with something softer.
👨‍💻 Code improvements:
- Rewrite JS file (To prepare step by step the architecture with a bundler, maybe a lib/framework)
- Rewrite CSS by adding vars (To have some consistency in our code)

feat: Improve pipeline view

---

web/static/pipeline/main.css

fix: Break word to avoid scrolling on x axis

---

web/static/app.css
web/static/pipeline/index.js
web/static/pipeline/main.css
web/templates/layout.tmpl
web/templates/pipeline.tmpl

* Fix #29: I enrich logs with a link element when I see something begin by http/https. The regex is very simple, but I think it's enough for the moment.
* Fix #36: Adding a message while waiting (ping @vbehar)
* The last one is for @jstrachan 😉  I saw that you use this app on phone. I improve a little the pipeline view on mobile/tablet.
Links to #28.
Thats looks like :

feat: Little Improvements on pipeline view

---

.lighthouse/jenkins-x/Kptfile
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml

update jenkins-x (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (c299962020e644b698090e61d43169e5c26720bf) to master (8b4e9b8183ae243434f4d26669229212726ee229)

chore: ugprade pipeline

---

charts/jx-pipelines-visualizer/templates/istio.yaml
charts/jx-pipelines-visualizer/values.yaml

Signed-off-by: Patrick Lee Scott <pat@patscott.io>

feat: istio toggle to create virtualservice for provided gateway

---

web/templates/archived_logs.tmpl

fix: bad path in archived_logs

---

pipeline.go
store.go
web/handlers/functions/links.go
web/handlers/router.go
web/templates/home.tmpl

only implemented for github for the moment (also doesn't support github enterprise yet)

feat: add direct links to repo, pr/branch, author

---

store.go
web/static/app.css
web/static/home/index.js
web/templates/home.tmpl

instead of the latest pipelines
@florianorpeliere what do you think? feel free to change the CSS if needed ;-)

feat: display the number of pipelines for each status

---

informer.go
store.go
web/handlers/branch.go
web/handlers/functions/pipeline_counts.go
web/handlers/home.go
web/handlers/owner.go
web/handlers/repository.go
web/handlers/router.go
web/static/app.css
web/static/home/index.js
web/templates/home.tmpl

with:
- top statuses
- top repositories
- top authors
- top durations

feat: display cards on the homepage

---

go.mod
go.sum
web/static/app.css
web/static/pipeline/index.js
web/static/pipeline/main.css
web/templates/archived_logs.tmpl
web/templates/pipeline.tmpl

Hey !
Yes ! 
Now, we display collapsible content by step.
* When a pipeline is finished, we put the timer in the same line (at the beginning of the line)
* By default, steps are closed.
* We have a button to open/close all the steps.
* Add status icon on each step 
* Re-arrange JS code
* Fix bugs

feat: Collapse steps

---

web/static/pipeline/index.js
web/templates/pipeline.tmpl

when the build logs have been garbage collected and not found in the long term storage
fixes #55

fix: error msg was not displayed

---

.lighthouse/jenkins-x/release.yaml

so that `feat:` PRs will produce new minor versions

chore: use semantic releases

---

cmd/server/main.go
informer.go
pipeline_running.go
web/handlers/functions/links.go
web/handlers/router.go
web/handlers/running.go
web/handlers/running_events.go
web/static/app.css
web/static/running/index.js
web/templates/home.tmpl
web/templates/running.tmpl

to easily see which steps are running in real time in the cluster

feat: new webpage with all running pipelines/stages/steps

---

.lighthouse/jenkins-x/Kptfile
.lighthouse/jenkins-x/pullrequest.yaml
.lighthouse/jenkins-x/release.yaml
.lighthouse/jenkins-x/triggers.yaml

update jenkins-x (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (e683ec9b73e4faff14b8cd61c19791bc95dd01fb) to master (113ee4f5634c31271c29467463cc104ab727ef68)

chore: update pipeline-catalog

---

go.mod
web/handlers/logs.go
web/handlers/logs_live.go
web/handlers/pipeline.go

fix: support repos with underscore

---

go.sum
web/handlers/logs_live.go

fix: handle live logs for repos with underscore

---

charts/jx-pipelines-visualizer/templates/deployment.yaml
charts/jx-pipelines-visualizer/values.yaml
cmd/server/main.go
web/handlers/functions/pipeline.go
web/handlers/router.go
web/static/pipeline/index.js
web/templates/pipeline.tmpl

use grafana tempo to open the pipeline trace - if available

feat: open pipeline trace URL

---

web/static/pipeline/index.js

fix: don't fail if the trace button is not there

---

charts/jx-pipelines-visualizer/templates/ingress.yaml
charts/jx-pipelines-visualizer/values.yaml

and make it configurable using the `ingress.class` value

fix(chart): set the ingress class to nginx by default

---

web/handlers/logs_live.go

for people still using a meta pipeline, and trying to see the live logs while the meta pipeline is running, they can only see the logs from the meta pipeline, not the real build pipeline - unless they reload the page.
this fix automatically reload the logs after the meta pipeline is finished, to ensure the user will see all the logs from all the pipelineruns in the pipeline
related to https://github.com/jenkins-x-plugins/jx-build-controller/issues/30

fix: live logs with meta pipelines

---

charts/jx-pipelines-visualizer/values.yaml

so that we can get tekton pipelines

fix: fix missing RBAC permission

---

web/static/pipeline/index.js

fix: logs errors should be visible by default

---

charts/jx-pipelines-visualizer/templates/deployment.yaml
charts/jx-pipelines-visualizer/values.yaml

fixes #123
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>

feat: add support for s3 compatible buckets

---

charts/jx-pipelines-visualizer/templates/ingress.yaml
charts/jx-pipelines-visualizer/values.yaml

fix: add support for v1 ingress
